### ISSUE TITLE
MacOS Mojave

### ISSUE THREAD

**Issue by Martus0** [cl3m/MiddleClick#24]
After upgrade to Mojave MiddleClick stopped working. Does it require any change to the code or can be fixed by a change in the OS? :)

**Comment by tiagopinheirods** [comment]
adjustments> security and accessibility > accessibility

![captura de tela 2018-09-28 as 10 52 39](https://user-images.githubusercontent.com/20006869/46212675-ef808000-c30c-11e8-835d-7a98880ab524.png)
