### ISSUE TITLE
MiddleClick stopped working macOS Big Sur (v11.0.1)

### ISSUE THREAD

**Issue by kuzonthedon** [cl3m/MiddleClick#31]
New update, running this on 2018 macbook pro, middleclick is open and seems to be running well but the funtionality is gone.

**Comment by jpaulickcz** [comment]
Same here

**Comment by cl3m** [comment]
this fork is not maintained, check out this solution: https://github.com/markhughes/MiddleTap/issues/2#issuecomment-730500106
